### PR TITLE
Add pxd files for imaging observers

### PR DESCRIPTION
**Pull request by munechika-koyo**
To inherit the imaging observers class defined in pyx files, I created equally name pxd files.

### CODE REVIEW

**Comment by munechika-koyo** [comment]
I also fixed the value of the default pixel parameter because it was different from what is written in docstring.

**Comment by CnlPepper** [comment]
Some of the commits change the default pixels dimensions. Could you please remove the offending lines?

**Comment by munechika-koyo** [comment]
I changed them following the docstrings default values. Should I restore them and modify docstrings?

**Comment by CnlPepper** [comment]
Re-implemented and extended to all observers. See abe708bba00585699ee3a13f885e1e1c25db6c1d.

**Pull request closed without merging**
