### PR TITLE
Feature cone primitive

### PR DESCRIPTION
**Pull request by mattngc**
I've cleaned the cone code, added some documentation, and checked its all working. It should now be ready for merge into master.

### CODE REVIEW

**Comment by CnlPepper** [comment]
Thanks Matt, I'll have a nose through the code tomorrow. I did spot some debug print statements in the code which you forgot to remove. Have you pushed all your local commits?

**Comment by mattngc** [comment]
Yes, I've committed all my local commits. I thought I had cleaned up everything, but maybe not.

**Comment by CnlPepper** [comment]
btw I honestly don't understand why you need this:
```
z = hit_point.z - EPSILON * normal.z
```
on line 346. I'm going to need to sketch this out and figure out what is going on.

**Comment by CnlPepper** [comment]
Ah bugger I've just found another logic mistake in the code... give me an evening and I'll see if I can figure out whet is going on.

**Pull request merged**
