### PR TITLE
Feature/pipeline data save

### LINKED ISSUE #207: All pipelines should have a save_data utility method
Currently, most of the pipelines have a save() utility method for saving the figure plotted during rendering. In many cases, its more useful to get the data as well in a sensible format. Perhaps this could be bundled into a utility on the pipelines.

### PR DESCRIPTION
**Pull request by mattngc**
Adds utility functions for saving the scientific data on pipelines. The format could be better but this is probably a user specific problem. Main this is it gives them a demo for working with / saving the data. Fixes #207.

### CODE REVIEW

**Comment by CnlPepper** [comment]
I think it would be better to implement this by adding setstate and getstate to the relevant classes rather than adding a save method. Then the user can just simply pickle the pipeline object.

**Comment by CnlPepper** [comment]
Or the frame object...

**Comment by mattngc** [comment]
Fair enough... I'll have a look at implementing the getstate and setstate methods instead.

**Comment by mattngc** [comment]
Moving all of this work to the new branch created by Alex, feature/pickle_raysect.
The reason for doing this is that #207 will now be absorbed into the bigger ticket #226 to ensure that all objects in the Raysect scenegraph can be pickleable. Its more appropriate to merge all this work together.

**Pull request closed without merging**
